echo "Custom commands list"
echo "culoare - changes text color"
echo "logout/exit - logout from the user account"
echo "chpass - change password of the curent user"
echo "whoami - shows user information"
echo "istoric - user commands history"
echo "istoric -c - empties the command history"
echo "raport - show information about user disk usage"
echo "delete - delete curent user"
echo "dogsay - the  dog says something"
echo "catsay - just a normal cat"
echo "whoismyfather - who is it?"
echo "dice - user vs computer dice game"
echo "sudo - no permission"